# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pr:
- master 

pool:
  vmImage: 'ubuntu-20.04'
  #name: Default

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  DOTNET_CLI_HOME: '/tmp/'

steps:
- checkout: self
  clean: true

- task: UseDotNet@2
  inputs:
    packageType: sdk
    version: '6.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet
    includePreviewVersions: false # Required for preview versions

- task: DotNetCoreCLI@2
  displayName: 'Restoring packages'
  inputs:
    command: 'restore'
    projects: '$(solution)'
    #includeNuGetOrg: true

- task: DotNetCoreCLI@2
  displayName: 'Building... $(buildConfiguration)'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    configuration: '$(buildConfiguration)'
  
- task: DotNetCoreCLI@2
  displayName: 'Publishing...'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: True
  
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'